# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.20'

RELEASE_GIT_HEAD = 'f4aecb271f83d6db4e2a67f4fa8ba7a8a1fab7f6'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'do76/yt-dlp'

ORIGIN = 'do76/yt-dlp'

_pkg_version = '2025.03.20'
