# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.21'

RELEASE_GIT_HEAD = '1116777a0245f2f6590195956d355a2739b4b013'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'do76/yt-dlp'

ORIGIN = 'do76/yt-dlp'

_pkg_version = '2025.03.21'
