# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.24'

RELEASE_GIT_HEAD = 'fb0da9422e6663913e70838cd902b442ab095120'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'do76/yt-dlp'

ORIGIN = 'do76/yt-dlp'

_pkg_version = '2025.03.24'
